server:
  port: 80
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
     # defaultZone: http://127.0.0.1:7002/eureka/,http://127.0.0.1:7001/eureka/
      defaultZone: http://127.0.0.1:7001/eureka/
  instance:
      prefer-ip-address: true
      instance-id: order80
      #客户端向服务器发送心跳的时间间隔 ，默认30s
      lease-expiration-duration-in-seconds: 1
      #服务端在最后一次收到心跳的等待时间，默认为90s
      lease-renewal-interval-in-seconds: 2
spring:
  application:
    name: order-service
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1
