server:
  port: 3370
spring:
  application:
    name: config-center
  cloud:
    config:
      server:
        git:
          uri: https://github.com/netbanner/springcloud-config.git
          username: netbanner
          password: 530626@kl
          search-paths:
            - springcloud-config
      label: master
  rabbitmq:
    host: localhost
    username: guest
    password: guest
    port: 5672
eureka:
  instance:
    prefer-ip-address: true
    instance-id: config-server
  client:
    service-url:
      defaultZone:  http://localhost:7001/eureka
logging:
  level:
    org:
      springframework:
        boot:
          autoconfigure:
            logging: info
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
